# Generated by Django 2.1.3 on 2019-05-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190430_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acess_Record',
            new_name='AcessRecord',
        ),
        migrations.AlterField(
            model_name='webpage',
            name='topic',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='webpage', to='myapp.Topic'),
        ),
    ]
