# Generated by Django 2.1.3 on 2019-05-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190503_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='topic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='webpage', to='myapp.Topic'),
        ),
    ]
