# Generated by Django 2.1.3 on 2019-05-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190503_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='topic',
            field=models.CharField(blank=True, max_length=345, unique=True),
        ),
    ]
