# Generated by Django 2.1.3 on 2019-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190503_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='topic',
            field=models.CharField(blank=True, max_length=345),
        ),
    ]
