# Generated by Django 2.1.3 on 2019-05-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190503_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acessrecord',
            name='name',
        ),
    ]
